spring:
  application:
    name: sundefa-start
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT
    username: test
    password: test
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  data:
    mongodb:
      uri: mongodb://192.168.26.128:27017/
      database: test

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: cn.sundefa.start.entity
  configuration:
    map-underscore-to-camel-case: true

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


logging:
  level:
    cn.sundefa.start.mapper: info

fw:
  swagger:
    enable: true
    description: quickStart项目
    version: 1.0
    contactName: Defa sun
    url: https://www.sundefa.cn/

